using System.Text.Json.Serialization;

namespace Common.Models.PerplexityApi.Common.Response;

/// <summary>
/// Represents the cost breakdown for an operation, including input, output, request, and total costs.
/// </summary>
public class Cost
{
    /// <summary>
    /// Gets the total cost associated with input tokens for the operation.
    /// </summary>
    [JsonPropertyName("input_tokens_cost")]
    public double InputTokensCost { get; init; }

    /// <summary>
    /// Gets the total cost associated with the output tokens generated by the operation.
    /// </summary>
    [JsonPropertyName("output_tokens_cost")]
    public double OutputTokensCost { get; init; }

    /// <summary>
    /// Gets the cost associated with the request.
    /// </summary>
    [JsonPropertyName("request_cost")]
    public double RequestCost { get; init; }

    /// <summary>
    /// Gets the total cost associated with the transaction or operation.
    /// </summary>
    [JsonPropertyName("total_cost")]
    public double TotalCost { get; init; }
}
